"""
Custom metrics defined in our Google Analytics account.
Names include the custom metric index and their scope, following
this specific pattern: CDX_SCOPE_NAME

There are 4 types of scopes: Hit, Session, User and Product.
HS (Hit Scope), SS (Session Scope), US (User Scope), PS (Product Scope).

These constants should be updated whenever we update the metrics on GA.
"""

CM1_HS_BRAND_PAGEVIEW = 'cm1'
CM2_PS_CALL_LEAD_DISPLAYED = 'cm2'
CM3_PS_CALL_LEAD_HIDDEN_VR = 'cm3'
CM4_PS_FORM_LEAD_DISPLAYED = 'cm4'
CM5_PS_FORM_LEAD_HIDDEN_VR = 'cm5'
CM6_PS_CLICK_LEAD_DISPLAYED = 'cm6'
CM7_PS_CLICK_LEAD_HIDDEN_VR = 'cm7'
CM8_PS_CALL_LEAD = 'cm8'
CM9_PS_CLICK_LEAD = 'cm9'
CM10_PS_FORM_LEAD = 'cm10'
CM11_PS_SESSION_LEAD = 'cm11'
CM12_HS_SECONDS_ENGAGED = 'cm12'
CM13_HS_VIDEO_SECONDS_WATCHED = 'cm13'
CM14_HS_VIDEO_PLAYS = 'cm14'
CM15_HS_VIDEO_COMPLETIONS = 'cm15'
CM16_HS_NOF_SEARCH_RESULTS = 'cm16'
CM17_HS_BLOG_PAGEVIEW = 'cm17'
CM18_HS_NEWS_ARTICLE_PAGEVIEW = 'cm18'
CM19_PS_VERIFIED_CALL_LEAD = 'cm19'
CM20_PS_VERIFIED_CLICK_LEAD = 'cm20'
CM21_PS_VERIFIED_FORM_LEAD = 'cm21'
CM22_PS_VERIFIED_LEAD = 'cm22'
CM23_HS_NOF_SEARCH_RESULTS = 'cm23'
CM24_HS_ERROR_PAGES = 'cm24'
CM25_HS_WIZ_NUMBER_STEPS = 'cm25'
CM26_HS_WIZ_CURRENT_STEP = 'cm26'
CM27_HS_WIZ_QUEST_TEXT = 'cm27'
CM28_HS_WIZ_ANSWER_TYPE = 'cm28'
CM29_HS_WIZ_NUMBER_AVAIL_ANSW = 'cm29'
CM30_HS_WIZ_START = 'cm30'
CM31_HS_WIZ_QUEST_SERVED = 'cm31'
CM32_HS_WIZ_QUEST_ANSWER = 'cm32'
CM33_HS_WIZ_QUESTION_ANSWERED = 'cm33'
CM34_HS_WIZ_OUTCOME = 'cm34'
CM35_HS_WIZ_NOF_BRANDS_MATCHED = 'cm35'
CM36_HS_WIZ_RESULT_DELIVERED = 'cm36'
CM37_HS_EMAIL_OPEN = 'cm37'
CM38_PS_CLICK_LEAD_DISPLAYED_VR = 'cm38'
CM39_PS_CALL_LEAD_DISPLAYED_VR = 'cm39'
CM40_PS_FORM_LEAD_DISPLAYED_VR = 'cm40'
CM41_PS_CALL_ME_NOW_DISPLAYED = 'cm41'
CM42_PS_CALL_ME_NOW_CLICKED = 'cm42'
