"""
These parameters are part of the Measurement Protocol definition.
More information can be found at:
developers.google.com/analytics/devguides/collection/protocol/v1/parameters
"""

VERSION = 'v'
HIT_TYPE = 't'
TRACKING_ID = 'tid'
USER_ID = 'uid'
USER_IP = 'uip'
CLIENT_ID = 'cid'
USER_AGENT = 'ua'
DATASOURCE = 'ds'
EVENT_CATEGORY = 'ec'
EVENT_ACTION = 'ea'
EVENT_LABEL = 'el'
EVENT_VALUE = 'ev'
EVENT_NON_INTERACTIVE = 'ni'
HIT_TYPE_EVENT = 'event'
DOCUMENT_HOSTNAME = 'dh'
TRANSACTION_ID = 'ti'
TRANSACTION_AFFILIATION = 'ta'
TRANSACTION_REVENUE = 'tr'
TRANSACTION_TAX = 'tt'
PRODUCT_ACTION = 'pa'
PRODUCT_ID = 'id'
PRODUCT_NAME = 'nm'
PRODUCT_CATEGORY = 'ca'
PRODUCT_BRAND = 'br'
PRODUCT_VARIANT = 'va'
PRODUCT_POSITION = 'ps'
PRODUCT_PRICE = 'pr'
PRODUCT_QUANTITY = 'qt'
CACHE_BUSTER = 'z'
