# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker', models.CharField(max_length=48)),
                ('endpoint', models.CharField(max_length=2048)),
                ('payload', models.TextField()),
                ('response_code', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
